import { defineField, defineType } from 'sanity'

export const blogPost = defineType({
  name: 'blogPost',
  title: 'Blog Posts',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Post Title',
      type: 'string',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published Date',
      type: 'datetime',
    }),
    defineField({
      name: 'scheduledPublishAt',
      title: 'Scheduled Publish Time',
      type: 'datetime',
      description: 'Set by the schedule feature — cron fires publish at this UTC time',
    }),
    defineField({
      name: 'pinnedForCommunities',
      title: 'Pinned for Communities',
      type: 'array',
      of: [{ type: 'string' }],
      description: "Community slugs (e.g. coronado-real-estate) — post appears in that community's Most Popular tab",
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Community Spotlight', value: 'community-spotlight' },
          { title: 'Community Development', value: 'community-development' },
          { title: 'News', value: 'news' },
          { title: 'Market Update', value: 'market-update' },
          { title: 'Buying Tips', value: 'buying-tips' },
          { title: 'Selling Tips', value: 'selling-tips' },
          { title: 'Local Interest', value: 'local-interest' },
          { title: 'Investment', value: 'investment' },
          { title: 'Home Ownership', value: 'home-ownership' },
          { title: 'Events', value: 'events' },
          { title: 'Financing', value: 'financing' },
        ],
      },
    }),
    defineField({
      name: 'vaQueuePriority',
      title: 'VA Queue Priority',
      type: 'number',
      description: 'Pin to top of VA queue. 0 = normal (default), 100 = top priority (Fed rate posts, breaking news). Higher = higher in queue.',
      initialValue: 0,
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      description: 'Short summary shown in blog listing and SEO description',
    }),
    defineField({
      name: 'authorName',
      title: 'Author Name',
      type: 'string',
      initialValue: 'Hedda Parashos',
      description: 'Byline shown on the published post',
    }),
    defineField({
      name: 'workflowStatus',
      title: 'Workflow Status',
      type: 'string',
      options: {
        list: [
          { title: 'Media Pending (hidden)', value: 'media_pending' },
          { title: 'Media Ready', value: 'media_ready' },
          { title: 'Publish Pending', value: 'publish_pending' },
          { title: 'Publishing', value: 'publishing' },
          { title: 'Scheduled', value: 'scheduled' },
          { title: 'Published (live)', value: 'published' },
          { title: 'Publish Failed', value: 'publish_failed' },
        ],
      },
      description: 'Controls visibility and publish state for the content machine workflow',
    }),
    defineField({
      name: 'oneupFacebookSubmissionId',
      title: 'OneUp Facebook Submission ID',
      type: 'string',
      description: 'Returned by OneUp after the Facebook post is submitted',
    }),
    defineField({
      name: 'oneupFacebookStatus',
      title: 'OneUp Facebook Publish Status',
      type: 'string',
      options: { list: ['pending', 'published', 'failed'] },
      description: 'Polled from OneUp after submission',
    }),
    defineField({
      name: 'oneupFacebookPublishedAt',
      title: 'OneUp Facebook Published At',
      type: 'datetime',
      description: 'When OneUp confirmed the Facebook post went live',
    }),
    defineField({
      name: 'facebookPostUrl',
      title: 'Facebook Post URL',
      type: 'url',
      description: 'URL of the published Facebook post (returned by OneUp)',
    }),
    defineField({
      name: 'socialCopy',
      title: 'Social Media Copy',
      type: 'text',
      rows: 3,
      description: 'Auto-generated Facebook post caption (editable by VA before publishing)',
    }),
    defineField({
      name: 'videoScript',
      title: 'Video Script',
      type: 'text',
      rows: 8,
      description: 'Auto-generated script for Hedda to record a short video summary of this article',
    }),
    defineField({
      name: 'socialDeclined',
      title: 'Social Posting Declined',
      type: 'boolean',
      description: 'Set to true when this post has been deliberately skipped for Facebook posting',
    }),
    defineField({
      name: 'videoUrl',
      title: 'Video URL',
      type: 'url',
      description: 'Vercel Blob URL of the uploaded video (used for YouTube + TikTok publishing)',
    }),
    defineField({
      name: 'videoThumbnailUrl',
      title: 'Video Thumbnail URL',
      type: 'url',
      description: 'Vercel Blob URL of the custom thumbnail for YouTube (optional)',
    }),
    defineField({
      name: 'youtubePostSubmissionId',
      title: 'YouTube Submission ID',
      type: 'string',
      description: 'Returned by OneUp after the YouTube post is submitted',
    }),
    defineField({
      name: 'tiktokPostSubmissionId',
      title: 'TikTok Submission ID',
      type: 'string',
      description: 'Returned by OneUp after the TikTok post is submitted',
    }),
    defineField({
      name: 'youtubePostUrl',
      title: 'YouTube Video URL',
      type: 'url',
      description: 'URL of the published YouTube video (returned by OneUp)',
    }),
    defineField({
      name: 'tiktokPostUrl',
      title: 'TikTok Video URL',
      type: 'url',
      description: 'URL of the published TikTok video (returned by OneUp)',
    }),
    defineField({
      name: 'oneupLinkedinSubmissionId',
      title: 'OneUp LinkedIn Submission ID',
      type: 'string',
      description: 'Returned by OneUp after the LinkedIn post is submitted',
    }),
    defineField({
      name: 'oneupXSubmissionId',
      title: 'OneUp X (Twitter) Submission ID',
      type: 'string',
      description: 'Returned by OneUp after the X/Twitter post is submitted',
    }),
    defineField({
      name: 'instagramPostSubmissionId',
      title: 'Instagram Submission ID',
      type: 'string',
      description: 'Returned by OneUp after the Instagram post is submitted',
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Thumbnail shown in blog listing and at top of post',
    }),
    defineField({
      name: 'heroBannerImage',
      title: 'Hero Banner Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Wide 4:1 banner (1920×480) shown at the top of the blog post page',
    }),
    defineField({
      name: 'body',
      title: 'Post Body',
      type: 'array',
      of: [
        { type: 'block' },
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', title: 'Alt Text', type: 'string' },
            { name: 'caption', title: 'Caption', type: 'string' },
          ],
        },
      ],
    }),
    defineField({
      name: 'metaTitle',
      title: 'SEO Title',
      type: 'string',
    }),
    defineField({
      name: 'metaDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'aiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      description: 'Mark if this post was created by the AI blog agent',
      initialValue: false,
    }),
    // ─── Enterprise video pipeline fields ─────────────────────────────────────
    defineField({
      name: 'videoLookId',
      title: 'Video Look ID',
      type: 'string',
      description: 'Per-post look override — blank means a look is picked automatically',
    }),
    defineField({
      name: 'videoDurationEstimateSec',
      title: 'Video Duration Estimate (sec)',
      type: 'number',
    }),
    defineField({
      name: 'enterpriseVideoJobId',
      title: 'Enterprise Video Job ID',
      type: 'string',
    }),
    defineField({
      name: 'enterpriseVideoStatus',
      title: 'Enterprise Video Status',
      type: 'string',
      options: { list: ['processing', 'completed', 'failed'] },
    }),
    defineField({
      name: 'videoScenes',
      title: 'Video Scenes',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'videoScene',
          fields: [
            defineField({ name: 'keyword', title: 'Keyword', type: 'string' }),
            defineField({ name: 'phrase', title: 'Phrase', type: 'string' }),
            defineField({ name: 'imageQuery', title: 'Image Query', type: 'string' }),
            defineField({ name: 'place', title: 'Place', type: 'string' }),
            defineField({ name: 'imageUrl', title: 'Image URL', type: 'url' }),
            defineField({ name: 'order', title: 'Order', type: 'number' }),
            defineField({ name: 'approved', title: 'Approved', type: 'boolean' }),
            defineField({
              name: 'source',
              title: 'Source',
              type: 'string',
              options: { list: ['search', 'generated', 'uploaded', 'map'] },
            }),
          ],
        },
      ],
    }),
    // ─── Refresh fields ────────────────────────────────────────────────────────
    defineField({
      name: 'refreshTier',
      title: 'Refresh Tier',
      type: 'string',
      options: {
        list: [
          { title: 'Evergreen (review every 12 months)', value: 'evergreen' },
          { title: 'Pillar (review every 6 months)', value: 'pillar' },
          { title: 'Competitive (review every 6 months)', value: 'competitive' },
          { title: 'Fast-Changing (review every 3 months)', value: 'fast-changing' },
          { title: 'Seasonal (review before season peak)', value: 'seasonal' },
          { title: 'News/Trend (review every 1–3 months)', value: 'news-trend' },
          { title: 'Money Page (review every 4 months)', value: 'money-page' },
        ],
      },
      description: 'Determines how frequently this post is reviewed for freshness. Auto-assigned from category if blank.',
    }),
    defineField({
      name: 'refreshExcluded',
      title: 'Exclude from Auto-Refresh',
      type: 'boolean',
      description: 'Set to true to permanently prevent this post from appearing in the refresh queue.',
    }),
    defineField({
      name: 'lastRefreshedAt',
      title: 'Last Refreshed At',
      type: 'datetime',
      description: 'When this post was last refreshed by the content refresh pipeline.',
    }),
    defineField({
      name: 'refreshCount',
      title: 'Refresh Count',
      type: 'number',
      initialValue: 0,
      description: 'Total number of times this post has been refreshed.',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'publishedAt', media: 'coverImage' },
    prepare({ title, subtitle, media }) {
      return {
        title,
        subtitle: subtitle ? new Date(subtitle).toLocaleDateString() : 'Draft',
        media,
      }
    },
  },
  orderings: [
    {
      title: 'Published Date (Newest)',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
  ],
})
