import Link from 'next/link'
import ExpansionListings from './ExpansionListings'

/**
 * Template for Sanity-backed expansion pages (communities, condo buildings,
 * lifestyle hubs) generated by the expansion-pages cron. Styled to sit
 * alongside the static community pages: brand burgundy/gold, serif display
 * headings, warm off-white sections.
 */

export interface ExpansionPageDoc {
  title: string
  name: string
  pageType: string
  heroTagline?: string
  heroDescription?: string
  stats?: Array<{ value: string; label: string }>
  sections?: Array<{ heading: string; paragraphs: string[] }>
  quickFacts?: Array<{ label: string; value: string }>
  faqs?: Array<{ question: string; answer: string }>
  idxLocation?: { city?: string; state?: string; neighborhood?: string }
  idxPropertyTypes?: string[]
  fallbackIdxLocation?: { city?: string; state?: string; neighborhood?: string }
  nearby?: Array<{ name: string; url: string }>
  publishedAt?: string
  slug: string
}

const BRAND = 'var(--brand,#58172a)'
const ACCENT = 'var(--accent,#eeca00)'

export default function ExpansionCommunityPage({ doc }: { doc: ExpansionPageDoc }) {
  const fallbackLabel = doc.fallbackIdxLocation?.neighborhood ?? doc.fallbackIdxLocation?.city ?? 'nearby communities'
  const faqJsonLd = (doc.faqs?.length ?? 0) > 0 ? {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: doc.faqs!.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  } : null

  return (
    <>
      {faqJsonLd && (
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      )}

      {/* ── HERO ─────────────────────────────────────────────── */}
      <section style={{ background: 'var(--brand-darker,#28000c)', padding: '88px var(--pad-x,60px) 72px', textAlign: 'center' }}>
        <nav aria-label="Breadcrumb" style={{ marginBottom: '28px' }}>
          <Link href="/" style={{ color: 'rgba(255,255,255,.4)', textDecoration: 'none', fontFamily: 'var(--font-label)', fontSize: '12px' }}>Palisade Realty</Link>
          <span style={{ color: 'rgba(255,255,255,.3)', margin: '0 8px' }}>/</span>
          <Link href="/communities" style={{ color: 'rgba(255,255,255,.4)', textDecoration: 'none', fontFamily: 'var(--font-label)', fontSize: '12px' }}>Communities</Link>
          <span style={{ color: 'rgba(255,255,255,.3)', margin: '0 8px' }}>/</span>
          <span style={{ color: 'rgba(255,255,255,.65)', fontFamily: 'var(--font-label)', fontSize: '12px' }}>{doc.name}</span>
        </nav>
        {doc.heroTagline && (
          <span style={{ display: 'inline-block', fontFamily: 'var(--font-label)', fontSize: '11px', fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: BRAND, background: ACCENT, padding: '5px 14px', borderRadius: '2px', marginBottom: '18px' }}>
            {doc.heroTagline}
          </span>
        )}
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(30px,4.5vw,56px)', fontWeight: 400, color: '#fff', letterSpacing: '-0.02em', lineHeight: 1.12, margin: '0 auto 18px', maxWidth: '820px' }}>
          {doc.title}
        </h1>
        {doc.heroDescription && (
          <p style={{ fontFamily: 'var(--font-body)', fontSize: '17px', color: 'rgba(255,255,255,.72)', maxWidth: '680px', margin: '0 auto', lineHeight: 1.7 }}>
            {doc.heroDescription}
          </p>
        )}
        {(doc.stats?.length ?? 0) > 0 && (
          <div style={{ display: 'grid', gridTemplateColumns: `repeat(${Math.min(doc.stats!.length, 4)}, minmax(120px, 1fr))`, gap: '12px', maxWidth: '760px', margin: '40px auto 0' }}>
            {doc.stats!.map((s, i) => (
              <div key={i} style={{ padding: '14px 8px', borderTop: '1px solid rgba(255,255,255,.16)' }}>
                <span style={{ display: 'block', fontFamily: 'var(--font-display)', fontSize: 'clamp(24px,3vw,36px)', color: ACCENT, letterSpacing: '-0.02em', lineHeight: 1.1, marginBottom: '6px' }}>{s.value}</span>
                <span style={{ display: 'block', fontFamily: 'var(--font-label)', fontSize: '10px', fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'rgba(255,255,255,.6)' }}>{s.label}</span>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* ── BODY SECTIONS ────────────────────────────────────── */}
      <section style={{ background: 'var(--off-white,#faf7f2)', padding: '72px var(--pad-x,60px)' }}>
        <div style={{ maxWidth: '760px', margin: '0 auto' }}>
          {doc.sections?.map((sec, i) => (
            <div key={i} style={{ marginBottom: '44px' }}>
              <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(24px,2.8vw,34px)', fontWeight: 400, color: 'var(--near-black,#1a0a0a)', letterSpacing: '-0.02em', margin: '0 0 16px' }}>
                {sec.heading}
              </h2>
              {sec.paragraphs?.map((p, j) => (
                <p key={j} style={{ fontFamily: 'var(--font-body)', fontSize: '16px', color: '#444', lineHeight: 1.8, margin: '0 0 16px' }}>{p}</p>
              ))}
            </div>
          ))}
        </div>
      </section>

      {/* ── QUICK FACTS ──────────────────────────────────────── */}
      {(doc.quickFacts?.length ?? 0) > 0 && (
        <section style={{ background: '#fff', padding: '64px var(--pad-x,60px)' }}>
          <div style={{ maxWidth: '980px', margin: '0 auto' }}>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(24px,2.8vw,34px)', fontWeight: 400, color: 'var(--near-black,#1a0a0a)', letterSpacing: '-0.02em', margin: '0 0 28px', textAlign: 'center' }}>
              {doc.name} at a Glance
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '14px' }}>
              {doc.quickFacts!.map((f, i) => (
                <div key={i} style={{ background: 'var(--off-white,#faf7f2)', border: '1px solid #eee5dd', borderRadius: '8px', padding: '18px 20px' }}>
                  <div style={{ fontFamily: 'var(--font-label)', fontSize: '10px', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#999', marginBottom: '8px' }}>{f.label}</div>
                  <div style={{ fontFamily: 'var(--font-body)', fontSize: '15px', fontWeight: 600, color: 'var(--near-black,#1a0a0a)', lineHeight: 1.5 }}>{f.value}</div>
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* ── LISTINGS (IDX with fallback) ─────────────────────── */}
      <section id="listings" style={{ background: 'var(--off-white,#faf7f2)', padding: '72px var(--pad-x,60px)' }} aria-labelledby="exp-listings-heading">
        <div style={{ maxWidth: '1400px', margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: '36px' }}>
            <span style={{ display: 'block', fontFamily: 'var(--font-label)', fontSize: '12px', fontWeight: 600, letterSpacing: '0.14em', textTransform: 'uppercase', color: BRAND, marginBottom: '12px' }}>Live MLS Data</span>
            <h2 id="exp-listings-heading" style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(28px,3.5vw,46px)', fontWeight: 400, color: 'var(--near-black,#1a0a0a)', letterSpacing: '-0.02em', margin: 0 }}>
              {doc.name} Listings
            </h2>
          </div>
          <ExpansionListings
            name={doc.name}
            primary={doc.idxLocation ?? { city: 'San Diego', state: 'CA' }}
            fallback={doc.fallbackIdxLocation ?? { city: 'San Diego', state: 'CA' }}
            propertyTypes={doc.idxPropertyTypes ?? ['house', 'condo', 'townhouse', 'multi_family']}
            fallbackLabel={fallbackLabel}
          />
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────── */}
      {(doc.faqs?.length ?? 0) > 0 && (
        <section style={{ background: '#fff', padding: '72px var(--pad-x,60px)' }}>
          <div style={{ maxWidth: '760px', margin: '0 auto' }}>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(24px,2.8vw,34px)', fontWeight: 400, color: 'var(--near-black,#1a0a0a)', letterSpacing: '-0.02em', margin: '0 0 28px' }}>
              Frequently Asked Questions
            </h2>
            {doc.faqs!.map((f, i) => (
              <div key={i} style={{ borderBottom: '1px solid #eee5dd', padding: '20px 0' }}>
                <h3 style={{ fontFamily: 'var(--font-body)', fontSize: '17px', fontWeight: 700, color: 'var(--near-black,#1a0a0a)', margin: '0 0 10px' }}>{f.question}</h3>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: '15px', color: '#555', lineHeight: 1.75, margin: 0 }}>{f.answer}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* ── NEARBY COMMUNITIES ───────────────────────────────── */}
      {(doc.nearby?.length ?? 0) > 0 && (
        <section style={{ background: 'var(--off-white,#faf7f2)', padding: '64px var(--pad-x,60px)' }}>
          <div style={{ maxWidth: '980px', margin: '0 auto', textAlign: 'center' }}>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(22px,2.5vw,30px)', fontWeight: 400, color: 'var(--near-black,#1a0a0a)', letterSpacing: '-0.02em', margin: '0 0 24px' }}>
              Explore Nearby Communities
            </h2>
            <div style={{ display: 'flex', gap: '14px', justifyContent: 'center', flexWrap: 'wrap' }}>
              {doc.nearby!.map((n, i) => (
                <Link key={i} href={n.url} style={{ display: 'inline-block', padding: '12px 26px', border: `1.5px solid ${BRAND}`, borderRadius: '999px', color: BRAND, fontFamily: 'var(--font-label)', fontSize: '13px', fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', textDecoration: 'none' }}>
                  {n.name} →
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* ── CTA ──────────────────────────────────────────────── */}
      <section style={{ background: 'var(--brand-darker,#28000c)', padding: '72px var(--pad-x,60px)', textAlign: 'center' }}>
        <span style={{ fontFamily: 'var(--font-label)', fontSize: '11px', fontWeight: 700, letterSpacing: '0.22em', textTransform: 'uppercase', color: ACCENT, display: 'block', marginBottom: '16px' }}>Ready to Make Your Move?</span>
        <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(26px,3.2vw,40px)', fontWeight: 400, color: '#fff', letterSpacing: '-0.02em', margin: '0 0 14px' }}>
          Your {doc.name} Experts
        </h2>
        <p style={{ fontFamily: 'var(--font-body)', fontSize: '16px', color: 'rgba(255,255,255,.65)', maxWidth: '480px', margin: '0 auto 28px', lineHeight: 1.7 }}>
          Whether you are buying or selling in {doc.name}, our team brings deep local knowledge and honest guidance to every step.
        </p>
        <div style={{ display: 'flex', gap: '14px', justifyContent: 'center', flexWrap: 'wrap' }}>
          <Link href="/contact" className="btn btn-brand">Talk to an Agent</Link>
          <Link href="/communities" className="btn btn-outline-white">All Communities</Link>
        </div>
      </section>
    </>
  )
}
