name: Deploy to Vercel Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel Production
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_E27fkByMI0FsH2tsspol7Ojj
          VERCEL_PROJECT_ID: prj_sR77aPS46WXF0oinu2UsLYlmAJhQ
